### ISSUE TITLE
[Bug]: Replies are too far from original comment

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1615] opened 2024-10-31 22:59 UTC
### What happened?

![CleanShot 2024-10-31 at 15 58 47@2x](https://github.com/user-attachments/assets/1197756e-15d1-4080-abb9-0bd68ccc12dc)

We refactored the comment section recently and seems replies have been pushed too far away from original comment

**Comment by aquibbaig** [comment] 2024-11-01 13:42
@bautistaaa I can take this up if possible. 

Here's a suggestion if y'all might like:
- Shifting the "x Replies" trigger to the left emphasizes connection with the original comment.
- I have reduced the bottom margin of the original comment from `1 rem to 0.5rem`

does this make sense?

<img width="457" alt="suggestion" src="https://github.com/user-attachments/assets/0bc0b5e8-ff48-467e-a691-9cc39c500aa4">

**Comment by nafisreza** [comment] 2024-11-01 14:00
I think this happened mainly for splitting reactions in two lines. By default the 2nd line of reacts are hidden, so it looks weird. Also, there is some extra padding in y-axis.
I agree with @aquibbaig. Maybe, it is better to move reply on the left, and last modified on right (if edited).

**Comment by satishkumarsajjan** [comment] 2024-11-04 15:14
I can take this. Kindly assign this to me.

**Comment by bautistaaa** [comment] 2024-11-04 15:15
> @bautistaaa I can take this up if possible. 
> 
> 
> 
> Here's a suggestion if y'all might like:
> 
> - Shifting the "x Replies" trigger to the left emphasizes connection with the original comment.
> 
> - I have reduced the bottom margin of the original comment from `1 rem to 0.5rem`
> 
> 
> 
> does this make sense?
> 
> 
> 
> <img width="457" alt="suggestion" src="https://github.com/user-attachments/assets/0bc0b5e8-ff48-467e-a691-9cc39c500aa4">
> 
> 

i think so. can you make a PR?

**Comment by bautistaaa** [comment] 2024-11-04 15:16
> I can take this. Kindly assign this to me.

i think @aquibbaig already did something but if not you can take it

**Comment by aquibbaig** [comment] 2024-11-04 19:02
<img width="491" alt="Comments section" src="https://github.com/user-attachments/assets/41d93ffc-eb83-4d16-9157-d8bca489b4c5">

@satishkumarsajjan @bautistaaa  Haven't started working on this yet; but was ideating around a few things to improve the UI. 

- The comments section suffers because of the fact that some of the actions (edit, share, and delete) are in the present in the DOM (w opacity-0) and are taking up un-necessary space. Any particular reason why it was designed in such a way? I think we can get away with a popover/dropdown interaction here.
- We can remove extra space in between the [original comment and the reply] & [org. comment & currently editing comment]. What if we take inspiration from something like reddit in this case? I think this looks clean and handles everything we'd want.

<img width="664" alt="Suggestion" src="https://github.com/user-attachments/assets/392741fe-780d-4025-8d78-12bc32cb6dd6">

**Comment by aquibbaig** [comment] 2024-11-04 19:04
and yes, @satishkumarsajjan feel free to take it up if you want to.

**Comment by aquibbaig** [comment] 2024-11-22 05:31
Note: This issue was partially fixed by #1640. 

#1652 is aimed at closing this for good.

**Comment by aquibbaig** [comment] 2024-11-27 11:00
@bautistaaa I think we can close this as well.

**Closed** 2024-11-27 13:01 UTC
Labels: bug
