### ISSUE TITLE
[Bug]: More challenges empty when not logged in

### ISSUE THREAD

**Issue by bautistaaa** [typehero/typehero#1383] opened 2024-01-03 18:52 UTC
### What happened?

navigate to https://typehero.dev/challenge/default-generic-arguments when not logged in and youll notice the more challenges section is empty. either hide or make sure its populated(probably the latter)

<img width="1107" alt="CleanShot 2024-01-03 at 10 51 45@2x" src="https://github.com/typehero/typehero/assets/3660667/f5b62678-ee80-4b0d-8ae2-b420360611b1">

**Comment by me-imfhd** [comment] 2024-01-03 20:37
The "More Challenges" section appears empty for users who aren't logged in, as it excludes successful submissions. Since users can't submit challenges when they're not logged in, we might consider whether this section needs to be populated for non-logged in users. If we introduce a popular challenges tracking feature for non-logged in users, we might not need the "More Challenges" section. Your decision ultimately matters.

**Comment by bautistaaa** [comment] 2024-01-03 20:38
i believe it’s populated on non beginner challenges while not logged in

**Comment by bautistaaa** [comment] 2024-01-03 20:39
it should be populated as it increases discoverability

**Comment by me-imfhd** [comment] 2024-01-03 20:44
> i believe it’s populated on non beginner challenges while not logged in

its not populated on any challenge right??  as i saw rn.
sorry if i did not get that correctly

**Comment by bautistaaa** [comment] 2024-01-03 20:46
you might be right!

**Comment by me-imfhd** [comment] 2024-01-03 21:38
raised this pr, and added screenshot to it, if i am not wrong by any chance this was what we wanted right?

**Comment by sital002** [comment] 2024-01-24 13:10
The issue is solved so it can be closed as completed.

**Closed** 2024-01-28 16:27 UTC
Labels: bug, good first issue
